<a href="https://colab.research.google.com/github/roitraining/PythonML/blob/master/Ch02-Numpy/02-02-NumPy-Creating_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Arrays

## Using the *array* Function to Create *ndarrays*
* Although it is possible to create an *ndarray* instance using \_\_new\_\_(), it is not the recommended approach
* The factory methods *array*, *zeros*, *ones*, and *empty* are preferred
* The *array* factory method is discussed here

### Do Now!
* Import numpy
* View the doc string of the numpy array function

In [1]:
import numpy as np

In [ ]:
help(np.array)

* The *array* function signature is:

       array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
       
    * *object* is 'array_like'
    * If *dtype* is not given, how is the type determined? \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    * Can the *dtype* be used to downcast the data stored in *object*? \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    * Which numpy method should be used for downcasting data being put into an *ndarray*? \_\_\_\_\_\_\_\_\_\_\_\_
    * Is the original object copied by default? \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    * What is the default order of the new *ndarray*? \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

### Do Now!
* Create a 5 element list of large integers
* Print the list
* Create a one-dimensional array from the list
* Print the array

In [3]:
l1 = [2**x for x in range(5)]
print ("l1 = ", l1)

l2 = [1, 2, 3, 4, 5]

l1 =  [1, 2, 4, 8, 16]


In [5]:
a1 = np.array(l1)
print ("a1 = ", a1, 'l1 = ', l1)
a1

a1 =  [ 1  2  4  8 16] l1 =  [1, 2, 4, 8, 16]


array([ 1,  2,  4,  8, 16])

### Do Now!
* View the doc string of the NumPy asarray function

In [ ]:
help(np.asarray)

### Do Now!
* Print the data type of the a1 array
* Use the asarray function to create a new array with dtype of int32 from a1
* Print the new array
* Is the result what you expected? \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

In [7]:
print ("a1.dtype = ", a1.dtype)
a1

a1.dtype =  int64


array([ 1,  2,  4,  8, 16])

In [10]:
m1 = [ 1.0, 2.0, 3.0]
m1 = [ 1, 2, 3.0]
m1

[1, 2, 3.0]

In [9]:
am1 = np.array(m1)
am1.dtype

dtype('float64')

In [ ]:
a2 = np.asarray(a1, dtype='int32')
print ("a2 = ", a2)
a2

### Do Now!
* Create a new list of 5 tuples with each tuple containing an integer and float
* Print the list
* Is the list a nested sequence? \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
* Create a new *ndarray* from the list
* Print the array
* Print the number of elements in the array
* Print the data type of the elements
  * Note that the integers in the original list have been up-casted to float
* Print the size of the array elements
* Print the number of bytes used to store the array data
* Print the number of dimensions of the array
* Print the shape of the array
* Print the strides of the array
* Print memory use information

In [ ]:
l2 = [(2 ** 54, 3.578 **10) for i in range(5)]
print ("l2 = ", l2)

a2 = np.array(l2)
print("a2 = ", a2)

print ("Number of elements, a2.size = ", a2.size)

print ("Data type of elements, a2.dtype =", a2.dtype)

print ("Size of the array elements, a2.itemsize = ", a2.itemsize)

print ("Total number of bytes used to store array data, a2.nbytes = ", a2.nbytes)

print ("Number of dimensions, a2.ndim =", a2.ndim)

print ("Shape of the array, a2.shape = ", a2.shape, " ==>  a", a2.shape[0], "X", a2.shape[1])

print ("Strides of the array = ", a2.strides)

print ("Memory use information = ", a2.flags)

In [ ]:
x = np.ones((2,3,4,5), dtype='float128')
x

## Summary of useful *ndarray* attributes
* For convenience, here a list of *ndarray* attributes
* Given x = np.ones( (2,3,4,5), dtype='float128')
   * ndim, the number of dimensions; e.g., 4
   * shape, the size of each dimension; e.g., (2,3,4,5)
   * dtype, the data type of each element; e.g., np.float128
   * itemsize, the size of each element 
        * Determined by the dtype; e.g., 16 bytes
   * size, the total number of elements in the array
        * Determined by the product of the shape sizes; e.g., 2 \* 3 \* 4 \* 5 = 120
   * nbytes, the total size of the array
        * Determine by the product of size and itemsize; e.g., 120 * 16 = 1920
   * strides, the number of bytes traversed in order to move from element to element in one dimension or across dimensions

## Using the *zeros* Function to Create *ndarrays*
* The *zeros* function, as its name suggest, creates an *ndarray* containing all zeros
* Unlike the *array* function, *zeros* doesn't take source data
* *zeros* includes a *shape* parameter for specifying the dimensions of the created *ndarray*

### Do Now!
* View the doc string of the numpy *zeros* function

In [ ]:
help(np.zeros)

### Do Now!
* Create a one dimensional, five-element array of zeros of dtype int32 
* Print the array
* Create a two dimensional,  5 X 7,  array of zeros of the default dtype
* Print the array
* Print the size and type of the elements
* Print the number of elements
* Print the total number of bytes required to store the data
* Print the number of dimensions

In [ ]:
z1 = np.zeros(5, dtype='int32')
print ("z1 = ", z1)

z2 = np.zeros( (5,7) )
print ("z2 = ", z2)

print ("Size of elements, z2.itemsize = ", z2.itemsize)
print ("Type of elements, z2.dtype", z2.dtype)
print ("Number of elements, z2.size = ", z2.size)
print ("Total number of data bytes, z2.nbytes = ", z2.nbytes)
print ("Number of dimensions, z2.ndim = ", z2.ndim)

## Using the *ones* Function to Create *ndarrays*
* The *ones* function works just like the *zeros* function except that it creates an *ndarray* containing all ones

### Do Now!
* View the doc string of the numpy *ones* function

In [ ]:
help(np.ones)

### Do Now!
* Create a four dimensional,  2 X 3 X 4 X 5,  array of ones of type 'complex64'
* Print the array
* Print the size and type of the elements
* Print the number of elements
* Print the total number of bytes required to store the data
* Print the number of dimensions
* Print the shape of the array

In [ ]:
o4 = np.ones( (2,3,4,5), dtype=np.complex64 )
print ("o4 = ", o4, "\n")

print ("Size of elements, o4.itemsize = ", o4.itemsize)
print ("Type of elements, o4.dtype", o4.dtype)
print ("Number of elements, o4.size = ", o4.size)
print ("Total number of data bytes, o4.nbytes = ", o4.nbytes)
print ("Number of dimensions, o4.ndim = ", o4.ndim)
print ("The shape of the array, o4.shape = ", o4.shape)

## Other Functions for Creating *ndarrays*
### Do Now!

### *np.arange*
* View the doc string for *np.arange*
* Print out an *ndarray* with elements rainging from 5 to 25 with a step of 4

In [ ]:
help(np.arange)

In [ ]:
print ("arange array = ", np.arange(5, 25, 4))

### *np.linspace*
* View the doc string for *np.linspace*
* Print an array of 50 numbers spaced over the interval 1 to 25

In [ ]:
help(np.linspace)

In [ ]:
print ("Evenly spaced array = ", np.linspace(1,25))

In [31]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.empty((3,3))
array2[:] = 2
array2[:1] = 3
print(array2)


print (array2)

print (array1 + array2)
print (array1 * array2)
print (array1 + 1)
print (array1 * 2)
x = array1.reshape(9)
print(x)
print(x[4:7])

np.save('/home/student/array1',array1)

[[3. 3. 3.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[3. 3. 3.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[ 4.  5.  6.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[ 3.  6.  9.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[1 2 3 4 5 6 7 8 9]
[5 6 7]


# End of notebook